NMS: 1
SEED: 10            # random seed

DEBUG: 1            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console

TRAIN_FLIST: ./data/pretrainlr.txt
VAL_FLIST: ./data/testlr.txt
TEST_FLIST: ./data/AntgroundtruthQML.txt
#TEST_FLIST: ./data/Antgroundtruthpric2_500.txt
#TEST_FLIST: ./data/antarcval.txt

TRAIN_MASK_FLIST: ./data/maskall.txt
VAL_MASK_FLIST: ./data/npymasksrant1000.txt
TEST_MASK_FLIST: ./data/npymaskQML.txt
#TEST_MASK_FLIST: ./data/npymaskpric2_500.txt


LR: 0.0001                    # learning rate
D2G_LR: 0.1                  # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2

INPUT_SIZE: 112               # input image size for training 0 for original size
MAX_ITERS: 2000000                # maximum number of iterations to train the model

L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 250        # style loss weight
CONTENT_LOSS_WEIGHT: 0.1      # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1  # adversarial loss weight

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size


SAMPLE_INTERVAL: 10         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 5               # number of images to sample
LOG_INTERVAL: 10000              # how many iterations to wait before logging training status (0: never)


MASK_REVERSE: 0                 # 1 reverse dunhuang, 0 no
MASK_THRESHOLD: 0               # 100 dunhuang


GPU: [0]            # list of gpu ids
BATCH_SIZE: 16                 # input batch size for training

SAVE_INTERVAL: 1000         # how many iterations to wait before saving model (0: never)
EVAL_INTERVAL: 1000             # how many iterations to wait before model evaluation (0: never)

TRAIN_SAMPLE_INTERVAL: 5000
EVAL_SAMPLE_INTERVAL: 10


TRAIN_SAMPLE_SAVE: ./result/train_sample
EVAL_SAMPLE_SAVE: ./result/eval_sample
TEST_SAMPLE_SAVE: ./result/testQML

MODEL_LOAD: 344000_InpaintingModel